server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
          filters:
            - StripPrefix=0
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
          filters:
            - StripPrefix=0
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
